[package]
name = "rust-grpc-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-grpc-demo-grpc = { path = "grpc" }
tonic = "0.9.2"
